### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by jletey**
@nikitavoloboev

### CODE REVIEW

**Comment by nikivdev** [comment]
Is it possible to make the badge fully black as others on `unknown`

2019-02-25 at 15 21

I am not sure if it will change color for other build statuses (like green / red)

**Comment by jletey** [comment]
It's currently `unknown` because you haven't merged this ... once you merge it, Travis will then run on the master branch and then the badge should say `passing`

> Is it possible to make the badge fully black

I'm not entirely sure if this is possible

> I am not sure if it will change color for other build statuses (like green / red)

Yes, for `passing` the color is green and for `failing` the color is red

**Comment by jletey** [comment]
@nikitavoloboev It doesn't look like Travis has been triggered ... is the repo enabled in your Travis account?

You can also trigger a build on the Travis website

**Comment by nikivdev** [comment]
done

**Comment by jletey** [comment]
Great!

**Pull request merged**
