### PR TITLE
Add the ability to parse a line with a link and a description

### PR DESCRIPTION
**Pull request by jletey**
Here's a rough draft ... tell me what you think

### CODE REVIEW

**Comment by nikivdev** [comment]
I tried it with:

```
func TestParseLinkWithDescription(t *testing.T) {
	assert := assert.New(t)
	v := "- [Effective Go](https://golang.org/doc/effective_go.html)"
	result := ParseLinkWithDescription(v)
	assert.Equal(result["Title"], "Effective Go", "Check to see if the title is correct")
	assert.Equal(result["Link"], "https://golang.org/doc/effective_go.html", "Check to see if the link is correct")
	assert.Equal(result["Description"], "", "Check to see if the description is correct")
}
```

And go test failed. Can we test what happens if there is no description too?

**Comment by jletey** [comment]
Sure ... working on it

**Comment by nikivdev** [comment]
Speaking of using this PR to solve https://github.com/nikitavoloboev/alfred-learn-anything/issues/9, are you on mac or windows. And if on mac, do you have [Alfred](https://www.alfredapp.com)? :)

**Comment by jletey** [comment]
I'm on Mac ... but I don't have Alfred

**Comment by jletey** [comment]
Also, can you take a look at nikitavoloboev/license-up#28

**Comment by jletey** [comment]
When we don't have a description, the regex completely changes ... how exactly do you want to go about checking if there is a description.

Regex for link without description: `(?m)^- \[([^]]+)\]\(([^)]+)\)$`
Regex for link with description: `(?m)^- \[([^]]+)\]\(([^)]+)\) - (.+)$`

**Comment by nikivdev** [comment]
It has to be all encompassing.

The use case if to parse a file like this:

https://github.com/learn-anything/books

And extract all the links (books + # Other) inside the file to some data structure.

**Comment by nikivdev** [comment]
If there is no description, it should only return the title and URL (those are bound to be there).

**Comment by nikivdev** [comment]
> but I don't have Alfred

That's a shame. It's a pretty amazing tool. Would definitely recommend. 🚀

There's lots of workflows for it too https://github.com/learn-anything/alfred-workflows#readme

**Comment by jletey** [comment]
> That's a shame. It's a pretty amazing tool. Would definitely recommend. 🚀

I know it's an amazing tool ... but the problem is that they charge for workflows

**Comment by nikivdev** [comment]
> but the problem is that they charge for workflows

Can send your PayPal, I can sponsor a license for you. 🙂

**Comment by jletey** [comment]
> Can send your PayPal, I can sponsor a license for you. 🙂

I don't have a PayPal account ... thank you though, that's very kind of you!

**Comment by jletey** [comment]
Should we change the function name from `ParseLinkWithDescription` to just `ParseLink`?

**Comment by nikivdev** [comment]
> `ParseLinkWithDescription` to just `ParseLink`

yes

**Comment by nikivdev** [comment]
> from `ParseLinkWithDescription` to just `ParseLink`

And do the error handling there in case there is no description. I believe there is none currently.

**Comment by jletey** [comment]
> And do the error handling there in case there is no description. I believe there is none currently.

There should be a test case called `TestParseLinkWithoutDescription`

**Comment by nikivdev** [comment]
> There should be a test case called `TestParseLinkWithoutDescription`

Or maybe just `TestParseLink` and inside it test a link with description and one without and check for outputs. As well as some other text like `blargh` to check if handles this case properly too.

**Comment by jletey** [comment]
Doing that now

**Comment by jletey** [comment]
@nikitavoloboev How does it look now?

**Comment by nikivdev** [comment]
Works great. Awesome!

**Comment by jletey** [comment]
Great! So is it now usable for your knowledge and other projects?

**Comment by nikivdev** [comment]
Will have to check. Will need few minutes/hours. 😅

**Comment by jletey** [comment]
Got it

**Comment by nikivdev** [comment]
> So is it now usable for your knowledge and other projects?

Actually for https://github.com/nikitavoloboev/knowledge/issues/25 it won't work as Imgur link embeds are of different format. Will have to write code specifically for parsing image embeds.

```
![](https://i.imgur.com/ZVPjkzh.png)
```

^ Is image embed.

**Comment by jletey** [comment]
I see ... you can probably just copy and paste the code for `ParseLink` into `ParseImgurLink` and then change up the regex

I can try to do this if you'd like

**Comment by nikivdev** [comment]
Opened #15

**Pull request merged**
